# Phase 1 - Exploratory Data Analysis

In [63]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import scipy.stats as stats
from pathlib import Path
import time

data_dir = Path("141")
if not data_dir.is_dir():
    data_dir = Path("IAU-project") / "141"
data_dir = data_dir.resolve()
data_dir

WindowsPath('C:/Users/David/Documents/IAU/IAU-project/141')

### EDA - gateways.csv

In [24]:
gateways = pd.read_csv(data_dir / "gateways.csv")
gateways.head()

ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 2

As can be seen above, the dataset does not load correctly, throwing a ParserError.
An inspection of raw data has to be performed using the "head" command in Bash.

In [ ]:
!head 141/gateways.csv # TODO fix relative path of the csv

vendor;firmware_version;Ipv4;unitId;depotId;signalDbm;technician;gatewayId;lastSeen
Paiva e Filhos;v1.2.5;240.222.226.112;1613;96;-61.00000;Gaspar Gomes-Faria;GW-00000;2024-08-20
Carlson-Spears;v3.4.1;180.162.46.233;1693;52;-53.10000;Dorit Nohlmans;GW-00001;01/26/2024, 00:00:00
Correia S/A;v3.4.1;181.63.29.198;1492;19;-68.60000;Stacy Wolfe;GW-00002;14 Dec 2024
Rosenow GmbH & Co. KGaA;v2.7.0;158.184.142.148;903;64;-67.30000;Ing. Francoise Carsten;GW-00003;2024/12/13
Cardoso;v2.7.0;200.236.47.63;935;29;-58.20000;Pedro Costa;GW-00004;2024-05-14
Mälzer;v2.7.0;43.96.253.5;1816;75;-62.00000;Pedro Carneiro;GW-00005;05/29/2024, 00:00:00
Hübel Ebert GmbH;v1.2.5;62.225.64.30;1232;79;-62.70000;Pedro Costa;GW-00006;2024/06/19
Machado Simões S/A;v1.2.5;216.199.39.27;466;80;-78.60000;Kevin Rodrigues;GW-00007;2024-08-18
Nguyen, Freeman and Roy;v1.2.5;15.185.225.238;1327;111;-80.60000;Timothy Larsen;GW-00008;16 Jan 2025

In [ ]:
!head 141/gateways.csv # TODO fix relative path of the csv

vendor;firmware_version;Ipv4;unitId;depotId;signalDbm;technician;gatewayId;lastSeen
Paiva e Filhos;v1.2.5;240.222.226.112;1613;96;-61.00000;Gaspar Gomes-Faria;GW-00000;2024-08-20
Carlson-Spears;v3.4.1;180.162.46.233;1693;52;-53.10000;Dorit Nohlmans;GW-00001;01/26/2024, 00:00:00
Correia S/A;v3.4.1;181.63.29.198;1492;19;-68.60000;Stacy Wolfe;GW-00002;14 Dec 2024
Rosenow GmbH & Co. KGaA;v2.7.0;158.184.142.148;903;64;-67.30000;Ing. Francoise Carsten;GW-00003;2024/12/13
Cardoso;v2.7.0;200.236.47.63;935;29;-58.20000;Pedro Costa;GW-00004;2024-05-14
Mälzer;v2.7.0;43.96.253.5;1816;75;-62.00000;Pedro Carneiro;GW-00005;05/29/2024, 00:00:00
Hübel Ebert GmbH;v1.2.5;62.225.64.30;1232;79;-62.70000;Pedro Costa;GW-00006;2024/06/19
Machado Simões S/A;v1.2.5;216.199.39.27;466;80;-78.60000;Kevin Rodrigues;GW-00007;2024-08-18
Nguyen, Freeman and Roy;v1.2.5;15.185.225.238;1327;111;-80.60000;Timothy Larsen;GW-00008;16 Jan 2025

The problem with loading the .csv file stems from the usage of semicolons instead of commas to separate individual fields. Adding the argument 'sep=";"' should fix the issue.

In [26]:
gateways = pd.read_csv(data_dir / "gateways.csv", sep=";")
gateways.head()

,vendor,firmware_version,Ipv4,unitId,depotId,signalDbm,technician,gatewayId,lastSeen
0,Paiva e Filhos,v1.2.5,240.222.226.112,1613.0,96,-61.0,Gaspar Gomes-Faria,GW-00000,2024-08-20
1,Carlson-Spears,v3.4.1,180.162.46.233,1693.0,52,-53.1,Dorit Nohlmans,GW-00001,"01/26/2024, 00:00:00"
2,Correia S/A,v3.4.1,181.63.29.198,1492.0,19,-68.6,Stacy Wolfe,GW-00002,14 Dec 2024
3,Rosenow GmbH & Co. KGaA,v2.7.0,158.184.142.148,903.0,64,-67.3,Ing. Francoise Carsten,GW-00003,2024/12/13
4,Cardoso,v2.7.0,200.236.47.63,935.0,29,-58.2,Pedro Costa,GW-00004,2024-05-14

In [27]:
gateways.dtypes

vendor                  str
firmware_version        str
Ipv4                    str
unitId              float64
depotId               int64
signalDbm           float64
technician              str
gatewayId               str
lastSeen                str
dtype: object

In [29]:
gateways.info()

<class 'pandas.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   vendor            16000 non-null  str
 1   firmware_version  16000 non-null  str
 2   Ipv4              16000 non-null  str
 3   unitId            2000 non-null   float64
 4   depotId           16000 non-null  int64
 5   signalDbm         16000 non-null  float64
 6   technician        16000 non-null  str
 7   gatewayId         16000 non-null  str
 8   lastSeen          16000 non-null  str
dtypes: float64(2), int64(1), str(6)
memory usage: 2.1 MB

In [45]:
gateways[gateways['unitId'].isnull()]

,vendor,firmware_version,Ipv4,unitId,depotId,signalDbm,technician,gatewayId,lastSeen
2000,Villanueva-Flynn,v3.4.1,248.174.223.115,NaN,65,-71.5,Simão Leal,GW-02000,2024/09/06
2001,Coleman-Sanford,v2.7.0,79.32.235.121,NaN,54,-64.3,Ismael Reis,GW-02001,2024/01/05
2002,Villanueva-Flynn,v3.4.1,217.252.155.140,NaN,5,-91.3,Monique Neuschäfer,GW-02002,"05/09/2024, 00:00:00"
2003,Carlson-Spears,v1.2.5,152.43.254.180,NaN,47,-52.3,Carrie Campbell,GW-02003,20 Sep 2024
2004,Leal S.A.,v1.2.5,236.214.139.14,NaN,61,-53.7,Robert Taylor,GW-02004,"08/14/2024, 00:00:00"
...,...,...,...,...,...,...,...,...,...
15995,Coleman-Sanford,v3.4.1,44.75.88.240,NaN,23,-52.5,Timothy Larsen,GW-15995,03 May 2024
15996,Maia S/A,v1.2.5,137.222.49.158,NaN,98,-78.9,Pedro Costa,GW-15996,04 Aug 2024
15997,Villanueva-Flynn,v2.7.0,50.38.25.84,NaN,76,-80.1,Suzanne Schacht,GW-15997,"11/24/2024, 00:00:00"
15998,Rosenow GmbH & Co. KGaA,v3.4.1,168.129.77.228,NaN,0,-73.5,Keith Rodriguez,GW-15998,2024/04/25
15999,Cardoso,v2.7.0,55.186.204.156,NaN,58,-67.8,Robert Taylor,GW-15999,"09/21/2024, 00:00:00"

Upon first inspection, two issues present themselves:
* Unit ID numbers stored as float values
* 14 000 null Unit ID values

First, NaN unit IDs will be removed.
Then, unit IDs will be converted to strings, not integers, since they serve as identification numbers, not numbers to do integer operations with. 
The index of the DataFrame will also be set to gateway ID.

In [ ]:
gateways1 = gateways # TODO safety measure, change to real dataset later 
gateways1 = gateways.dropna()
gateways1['unitId'] = gateways1['unitId'].astype(int) # this is to drop the decimal place
gateways1['unitId'] = gateways1['unitId'].astype(str)
gateways1 = gateways1.set_index("gatewayId")
gateways1

,vendor,firmware_version,Ipv4,unitId,depotId,signalDbm,technician,lastSeen
gatewayId,,,,,,,,
GW-00000,Paiva e Filhos,v1.2.5,240.222.226.112,1613,96,-61.0,Gaspar Gomes-Faria,2024-08-20
GW-00001,Carlson-Spears,v3.4.1,180.162.46.233,1693,52,-53.1,Dorit Nohlmans,"01/26/2024, 00:00:00"
GW-00002,Correia S/A,v3.4.1,181.63.29.198,1492,19,-68.6,Stacy Wolfe,14 Dec 2024
GW-00003,Rosenow GmbH & Co. KGaA,v2.7.0,158.184.142.148,903,64,-67.3,Ing. Francoise Carsten,2024/12/13
GW-00004,Cardoso,v2.7.0,200.236.47.63,935,29,-58.2,Pedro Costa,2024-05-14
...,...,...,...,...,...,...,...,...
GW-01995,Lopes Correia e Filhos,v2.7.0,249.32.194.66,689,116,-74.2,Hanife Jacobi Jäckel,2024/04/04
GW-01996,Villanueva-Flynn,v1.2.5,30.100.123.84,295,96,-65.3,Filipe Abreu,30 Jun 2024
GW-01997,Moreira,v2.7.0,145.228.30.34,716,51,-72.0,Manuel Costa,"09/29/2024, 00:00:00"
GW-01998,Barnett-Stone,v1.2.5,173.83.34.130,989,100,-60.3,Beata Margraf,"12/08/2024, 00:00:00"
GW-01999,Leal S.A.,v2.7.0,188.217.238.172,1996,75,-65.8,Lisa Haney,05 Jul 2024

In [ ]:
from datetime import datetime

def parse_last_seen(value: str) -> datetime:
    """Parse one lastSeen value from any format used in gateways.csv."""
    formats = ("%Y-%m-%d", "%m/%d/%Y, %H:%M:%S", "%d %b %Y", "%Y/%m/%d")
    for date_format in formats:
        try:
            return datetime.strptime(value, date_format)
        except ValueError:
            continue
    raise ValueError(f"Unsupported lastSeen date: {value!r}")

gateways2 = gateways1.copy()
gateways2["lastSeen"] = pd.to_datetime(gateways2["lastSeen"].map(parse_last_seen))
gateways2[["lastSeen"]].head()

### EDA - readings.csv

In [46]:
readings = pd.read_csv(data_dir / "readings.csv")
readings.head()

ParserError: Error tokenizing data. C error: Expected 1 fields in line 12, saw 2

Once again, the dataset does not load correctly, throwing a ParserError.
An inspection of raw data has to be performed using the "head" command in Bash.

In [ ]:
!head 141/readings.csv # TODO fix relative path of the csv

==> 141/readings.csv <==
unitId	tsCycle	current_motor	dp_filter	oilTemperature	reservoir_pressure	vibration_rms	Flowmeter	temp_bearing	dewpointDischarge	auxCurrent	failure
U00446	12 Nov 2023	4.38454	26.89302	65.11293	8.86318	2.06751	26.44157	70.62623	6.31825	1.88395	0
U00406	2023-09-25	6.49560	10.29036	58.61599	8.19517	1.21185	26.04481	73.12358	16.95198	3.59209	0
U00045	06 May 2023	5.62191	28.10412	53.73762	7.86230	1.74962	36.58353	61.40743	6.09235	2.22038	0
U01178	23 Jun 2023	7.02885	27.00850	47.26967	8.99546	7.28034	28.66149	62.33382	11.94870	2.14021	0
U01900	2023-12-24	4.70894	30.38483	56.61160	7.93272	2.14559	27.91020	69.58315	10.99307	3.22927	0
U00605	18 May 2023	6.30607		61.45955	8.44170	1.93848	29.71545	72.73637	8.18684	2.55253	0
U00844	30 Sep 2023	5.30544	10.46564	58.28968	8.45882	3.02270	24.20157	68.68838	3.20280	1.69108	1
U01980	2023-04-17	2.84162	21.84226	80.64701	9.08212	2.55332	29.13459	69.75218	8.69760	2.59577	0
U01647	2023-02-05	5.57649	33.75587	62.12043	8.71992	5.88114	27.60684	72.68872	8.15566	0.99277	0

==> //TODO <==

head: cannot open ';' for reading: No such file or directory
head: cannot open 'fix' for reading: No such file or directory
head: cannot open 'relative' for reading: No such file or directory
head: cannot open 'path' for reading: No such file or directory
head: cannot open 'of' for reading: No such file or directory
head: cannot open 'the' for reading: No such file or directory
head: cannot open 'csv' for reading: No such file or directory

Since the separator seems to be whitespace, we can verify with the 'cat -A' command.

In [50]:
!head 141/readings.csv | cat -A

unitId^ItsCycle^Icurrent_motor^Idp_filter^IoilTemperature^Ireservoir_pressure^Ivibration_rms^IFlowmeter^Itemp_bearing^IdewpointDischarge^IauxCurrent^Ifailure$
U00446^I12 Nov 2023^I4.38454^I26.89302^I65.11293^I8.86318^I2.06751^I26.44157^I70.62623^I6.31825^I1.88395^I0$
U00406^I2023-09-25^I6.49560^I10.29036^I58.61599^I8.19517^I1.21185^I26.04481^I73.12358^I16.95198^I3.59209^I0$
U00045^I06 May 2023^I5.62191^I28.10412^I53.73762^I7.86230^I1.74962^I36.58353^I61.40743^I6.09235^I2.22038^I0$
U01178^I23 Jun 2023^I7.02885^I27.00850^I47.26967^I8.99546^I7.28034^I28.66149^I62.33382^I11.94870^I2.14021^I0$
U01900^I2023-12-24^I4.70894^I30.38483^I56.61160^I7.93272^I2.14559^I27.91020^I69.58315^I10.99307^I3.22927^I0$
U00605^I18 May 2023^I6.30607^I^I61.45955^I8.44170^I1.93848^I29.71545^I72.73637^I8.18684^I2.55253^I0$
U00844^I30 Sep 2023^I5.30544^I10.46564^I58.28968^I8.45882^I3.02270^I24.20157^I68.68838^I3.20280^I1.69108^I1$
U01980^I2023-04-17^I2.84162^I21.84226^I80.64701^I9.08212^I2.55332^I29.13459^I69.75218^I8.69760^I2.59577^I0$
U01647^I2023-02-05^I5.57649^I33.75587^I62.12043^I8.71992^I5.88114^I27.60684^I72.68872^I8.15566^I0.99277^I0$

'^I' tells us the separator is a \t (tab) character, allowing us to use the read_csv() command correctly.

In [52]:
readings = pd.read_csv(data_dir / "readings.csv", sep='\t')
readings.head()

,unitId,tsCycle,current_motor,dp_filter,oilTemperature,reservoir_pressure,vibration_rms,Flowmeter,temp_bearing,dewpointDischarge,auxCurrent,failure
0,U00446,12 Nov 2023,4.38454,26.89302,65.11293,8.86318,2.06751,26.44157,70.62623,6.31825,1.88395,0
1,U00406,2023-09-25,6.49560,10.29036,58.61599,8.19517,1.21185,26.04481,73.12358,16.95198,3.59209,0
2,U00045,06 May 2023,5.62191,28.10412,53.73762,7.86230,1.74962,36.58353,61.40743,6.09235,2.22038,0
3,U01178,23 Jun 2023,7.02885,27.00850,47.26967,8.99546,7.28034,28.66149,62.33382,11.94870,2.14021,0
4,U01900,2023-12-24,4.70894,30.38483,56.61160,7.93272,2.14559,27.91020,69.58315,10.99307,3.22927,0